version: 1.2
workflows:
  - subclass: WDL 
    name: ExtractVariants
    primaryDescriptorPath: /workflows/ExtractVariants.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL 
    name: ExtractSeqFromASM
    primaryDescriptorPath: /workflows/seq_extract_from_asm.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: SVA_Typer
    primaryDescriptorPath: /workflows/sva_typer.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: ExtractInsertionMethylation
    primaryDescriptorPath: /workflows/extract_insertion_methylation.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: RenderRmarkdownReport
    primaryDescriptorPath: /workflows/render_rmarkdown.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: AssemblyCoverage
    primaryDescriptorPath: /workflows/assembly_coverage.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: AlignDiploidAssemblyToRef
    primaryDescriptorPath: /workflows/align_diploid_assembly_to_ref.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: RefSVAQc
    primaryDescriptorPath: /workflows/ref_sva_qc.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: ConcatenateAndProcessFiles
    primaryDescriptorPath: /workflows/concat_files_with_script.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: ParseLongestPureSegment
    primaryDescriptorPath: /workflows/parse_longest_pure_segment.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: MatchAssemblyHaplotypes
    primaryDescriptorPath: /workflows/match_assembly_haplotypes.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: ProcessRefSVAData
    primaryDescriptorPath: /workflows/process_ref_sva_data.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: FilterMEIVCF
    primaryDescriptorPath: /workflows/filter_mei_vcf.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: ProcessMEISVAData
    primaryDescriptorPath: /workflows/process_mei_sva_data.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: NominalAssociation
    primaryDescriptorPath: /workflows/nominal_association.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/
