version: 1.2
workflows:
  - subclass: WDL 
    name: ExtractVariants
    primaryDescriptorPath: /workflows/ExtractVariants.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: SVA_Typer
    primaryDescriptorPath: /workflows/sva_typer.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: ExtractInsertionMethylation
    primaryDescriptorPath: /workflows/extract_insertion_methylation.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: ConcatenateColumnFiles
    primaryDescriptorPath: /workflows/concat_files.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: RenderRmarkdownReport
    primaryDescriptorPath: /workflows/render_rmarkdown.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/
